(begin
	(define q_sarah (quote sarah))
	(define list_1234 (quote (1 2 3 4 5)))
	(define list_123 '(1 2 3))
	(define s 's)
	(define five (quote 5))
	(define six '6)
	(if (and (equal? q_sarah "sarah") (equal? list_1234 (list 1 2 3 4 5)) 
			(equal? list_123 (list 1 2 3)) (equal? s "s") (equal? five "5") 
			(equal? six "6"))
		(displayln "Passed")
		(displayln "Failed")))